---
# tasks main.yml for snaps
#- name: Import assert.yml
#  ansible.builtin.import_tasks:
#    file: assert.yml
#  run_once: yes
#  delegate_to: localhost

- name: Install snap requirement(s)
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ snapd_requirements }}"
  when:
    - snapd_requirements is defined

- name: Install snapd package(s)
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ snaps_apps }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - snapd_packages is defined

- name: Ensure snapd is running
  ansible.builtin.service:
    name: snapd
    state: started

- name: Install snapd apps
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('latest/stable') }}"
    classic: "{{ item.classic | default('false') }}"
    options: "{{ item.options | default('[]') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ snapd_apps }}"
  notify: restart snapd
